### ISSUE TITLE
Lora Module: Radio Library Errors 

### ISSUE THREAD

**Issue by jilshah2001** [MacRover/Rover#15]
Issue: 
Ran into two unique errors while testing the LORA boards. 
1. Error -2: Radio chip was not found during initialization. This can be caused by specifying the wrong chip type in the constructor (i.e. calling SX1272 constructor for SX1278 chip) or by a fault in your wiring (incorrect slave select pin). 
2. Error -705: SX126x timed out while waiting for the complete SPI command.

Attempted Fixes
1. Changed the pinout connections with the Arduino Uno to the following 
- DIO0 pin: 2
- DIO1 pin: 3
- RESET pin: 9
- NSS pin: 10
- MOSI: 11
- MISO: 12
- SCK: 13
Resulted in the second error.
Code used: https://github.com/jgromes/RadioLib/blob/master/examples/SX126x/SX126x_Transmit/SX126x_Transmit.ino

**Comment by jilshah2001** [comment]
Noticed, LoRa board inconsistencies with identical wiring, 
LoRa 1: Error -2 (loose j4 male connectors) 
LoRa 2:  Error -705

**Comment by jilshah2001** [comment]
Fixed the -705 error by switching the pinout connections with the Arduino Uno to the following:
BUSY: 2
DIO1 pin: 3
NSS pin: 10
MOSI: 11
MISO: 12
SCK: 13
GND: GND
![Data-TX-Working-LoRa1](https://user-images.githubusercontent.com/33742487/157589023-9a8f9761-355f-45f4-82d1-42031043986e.png)

**Comment by jilshah2001** [comment]
Lora Modules are transmitting and receiving data using the Arduino Uno and ESP32 Pico Kit. 

Arduino Uno (All pins connected to a digital input need to drop down to 3.3V)
BUSY: 2
DIO1 pin: 3
NRST: 9
NSS pin: 10
MOSI: 11
MISO: 12
SCK: 13
GND: GND
VCC: 3.3V

ESP32 Pico Kit
BUSY: 9
DIO1 pin: 2
NRST: 14
NSS pin: 5
MOSI: 23
MISO: 19
SCK: 18
GND: GND
VCC: 3.3V

Used Radiolab RX and TX example code with modifications to the code for the respective pins above.

![Screenshot 2022-03-28 202438](https://user-images.githubusercontent.com/33742487/160508770-7d529d7f-cb64-4b14-a36e-5091190bf903.png)

**Comment by emcauliffe** [comment]
Connection bug resolved, closing. Using #18 to track development progress on this milestone
