### ISSUE TITLE
Get xbox controller operation working for drive control

### ISSUE THREAD

**Issue by emcauliffe** [MacRover/Rover#40]
- [x] xbox controller jumps around constantly because the wrong info is being passed from the joy message
- [x] launch file doesn't seem to work properly? might have been a one-time thing
- [x] fix braking issue as the rover doesn't stop right away

**Comment by emcauliffe** [comment]
braking resolved with drive control heartbeat

**Comment by chosterto** [comment]
cmd vel repeater node added to controller launch file.
